var FilterConstants = {
  BOUND_PARAMS_RECEIVED: "BOUND_PARAMS_RECEIVED",
  MIN_RENT_RECEIVED: "MIN_RENT_RECEIVED",
  MAX_RENT_RECEIVED: "MAX_RENT_RECEIVED",
  MIN_BATHROOMS_RECEIVED: "MIN_BATHROOMS_RECEIVED",
  MAX_BATHROOMS_RECEIVED: "MAX_BATHROOMS_RECEIVED",
  MIN_BEDROOMS_RECEIVED: "MIN_BEDROOMS_RECEIVED",
  MAX_BEDROOMS_RECEIVED: "MAX_BEDROOMS_RECEIVED",
  LISTING_PARAMS_RECEIVED: "LISTING_PARAMS_RECEIVED",
};

module.exports = FilterConstants;
